### PR TITLE
Added new flag to create a CSV file containing data about the generated tokens

### PR DESCRIPTION
**Pull request by ziccardi**
# Motivation
We needed few more function, so the code has been rewritten to make it more maintainable.

# Changes
 - A new loader has been created for each of the objects to be loaded (App, Variants and Tokens)
 - Each loader implements the Runnable interface, so they are easily interchangeable
 - A Builder for each of the loader has been created to drive the user during the creation of the objects
 - The Observable pattern has been used to chain the loaders together and to log the output of the creation

### CODE REVIEW

**Comment by ziccardi** [comment]
ping @matzew @josemigallas

**Review by josemigallas — COMMENTED** [review]
Looks good to me! But, would not be better that the flag was -csv instead of -g?

Moreover, if the flag is not set, the aliases are all "TEST_TOKEN"? Because in [AGPUSH-2003](https://issues.jboss.org/browse/AGPUSH-2003) it says that all tokens must have the same alias.

**Comment by matzew** [comment]
yeah, we should have unique tokens. to cover a different test-case

**Comment by josemigallas** [comment]
The thing is.. do we really need to specify an alias if every single token has the same one? I thought the alias was a way to identify a group of devices, like a filter. But if all tokens have the same, we could simply not apply the filter and the notifications would be sent to all, am I wrong?

**Comment by josemigallas** [comment]
BTW this files should be added to the mock-data-loader .gitignore:
aerogear-mock-data-loader-1.0.0-SNAPSHOT
*.log.zip
*.log

**Comment by matzew** [comment]
> The thing is.. do we really need to specify an alias if every single token has the same one? I thought the alias was a way to identify a group of devices, like a filter. 

the alias is usually something unique, like an email address.

However, for the FCM case we used SAME alias as a hack, to prevent a submit to the Topics:
https://github.com/aerogear/aerogear-unifiedpush-server/blob/1.1.x-dev/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/token/TokenLoader.java#L130

https://github.com/aerogear/aerogear-unifiedpush-server/blob/1.1.x-dev/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/token/TokenLoaderUtils.java#L80

That's why - I guess there was likely some initial confusion, that's why Oleg and I did suggest (for Android) using SAME alias, to not submit the things through topics ;-)

**Review by josemigallas — APPROVED** [review]
Verified and working like charm

**Comment by matzew** [comment]
:+1:

**Pull request merged**
