### PR TITLE
Once Wiremock is up, we have to have a response for FCM

### PR DESCRIPTION
**Pull request by matzew**
@josemigallas @ziccardi @odra 

please review

### CODE REVIEW

**Comment by matzew** [comment]
I think over the break I will check out the FCM proxy from QE team, so we have both from there, instead of wiremock

**Comment by ziccardi** [comment]
LGTM

**Comment by josemigallas** [comment]
@matzew this is already done in the bash script. It creates a `fcm-send.json` with the response.

**Comment by matzew** [comment]
ah :-)

**Pull request closed without merging**
